browsersName=firefox
appURL=https://tutorialsninja.com/demo/
firstName=Maria
longfirstName=Asdfgjkkllllllllllllllllllllllllllllmmmmmmm
lastName=Jo
longlastName=adffghjjklikjhjkjlnjghjkkjhjklhfvnbmhiklk
telePhone=1236547890
password=asdfghjkl
longpassword=qwrretttttydfghjkasdfghjasdzfxghjkasdfghjkasdfghjkasdfghjku
missMatchPassword=qwerty
existingEmail=manu123@gmail.com
longEmail=adffghjjklikjhjkjlnjghjvvvvvvvvvvvvvvkkjhjklhfvnbmhiklk@gmail.com
invalidEmail=ghjkk
invalidEmail22=ghjkk1234@
invalidEmail2=ghjkk1234
invalidEmail3=ghjkk@gmail.
invalidPhone=fdghghj
